# Generated by Django 5.2 on 2025-06-19 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("distributor", "0001_initial"),
        ("marketing_rep", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fabricator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("institution", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=255)),
                ("sub_district", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                ("trade_license_img_url", models.URLField(max_length=512)),
                ("visiting_card_img_url", models.URLField(max_length=512)),
                ("profile_img_url", models.URLField(max_length=512)),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fabricators",
                        to="distributor.distributor",
                    ),
                ),
                (
                    "marketing_representative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fabricators",
                        to="marketing_rep.marketingrepresentative",
                    ),
                ),
            ],
        ),
    ]
