dist_upazila_map = {
    "B.Baria": [
        "B.Baria Sadar",
        "Bancharampur",
        "Sorail",
        "Kosba",
        "Akhaura",
        "Nasirnagar",
        "Ashugonj",
        "Bijoy Nagar",
        "Nobinagar",
    ],
    "Bagerhat": [
        "Fakirhat",
        "Bagerhat Sadar",
        "Mongla",
        "Rampal",
        "Mollahat",
        "Morelgonj",
        "Chitolmari",
        "Kachua(Bagerhat)",
        "Soronkhola",
    ],
    "Bandorban": [
        "Bandorban Sadar",
        "Ruma",
        "Alikadam",
        "Runagchori",
        "Thanchi",
        "Lama",
        "Naikhangchori",
    ],
    "Barguna": ["Barguna Sadar", "Pathorghata", "Taltali", "Amtoli", "Betagi", "Bamna"],
    "Barisal": [
        "Kotowali (Barisal)",
        "Gournodi",
        "Bakergonj",
        "Hizla",
        "Uzirpur",
        "Babugonj",
        "Banaripara",
        "Bondor(Barisal)",
        "Mehendigonj",
        "Kawnia (Barisal)",
        "Airport(Barisal)",
        "Agoiljhara",
        "Muladi",
        "Kazirhat",
    ],
    "Bhola": [
        "Char Fashion",
        "Bhola Sadar",
        "Lalmohon",
        "Borhanuddin",
        "Daulatkhan",
        "Monpura",
        "Tojumoddin",
        "Shashivoshon",
        "Dakhin Aicha",
    ],
    "Bogra": [
        "Bogra Sadar",
        "Dupchanchia",
        "Gabtoli(Bogra)",
        "Sherpur (Bogra)",
        "Sibgonj (Bogra)",
        "Adamdighi",
        "Kahalu",
        "Sonatola",
        "Sariakandi",
        "Nondigram",
        "Sajahanpur(Bogra)",
        "Dhunot",
    ],
    "Chandpur": [
        "Chandpur Sadar",
        "Hazigonj",
        "Motlob Uttar",
        "Motlob Dakhin",
        "Kochua (Chandpur)",
        "Faridgonj",
        "Motlob",
        "Haimachar",
        "Shahrasti",
    ],
    "Chapai Nababgonj": ["Nababgonj Sadar", "Gomostapur", "Nachol", "Bholahat"],
    "Chittagong": [
        "Kotowali (Ctg.)",
        "EPZ(CTG)",
        "Halishahar",
        "Bayezid",
        "Joralgong",
        "Potia",
        "Sitakundu",
        "Rangunia",
        "Sandip",
        "Bashkhali",
        "Hathazari",
        "Satkania",
        "Lohagara",
        "Puchlaish",
        "Khulshi",
        "Fatikchari",
        "Bondor (CTG)",
        "Akborshah",
        "Chadgaon",
        "Chandanaish",
        "Mirsorai",
        "Anowara",
        "Boalkhali",
        "Vujpur",
        "Rawzan",
        "Bakulia",
        "Pahartoli",
        "Potenga",
        "Double Mooring",
        "Kornafuly",
    ],
    "Chuadanga": ["Damurhuda", "Alamdanga", "Chuadanga Sadar", "Jibon Nagar"],
    "Comilla": [
        "Sadar Dakhkhin",
        "Comilla Sadar",
        "Debidder",
        "Daudkandi",
        "Laksam",
        "Chauddagram",
        "Chandina",
        "Burichang",
        "Nangolcoat",
        "Muradnagar",
        "Brammonpara",
        "Borura",
        "Meghna",
        "Titas",
        "Homna",
        "Monohorgonj",
    ],
    "Cox's Bazar": [
        "Ramu",
        "Cox's Bazar Sadar",
        "Chokoria",
        "Teknaf",
        "Moheskhali",
        "kutubdia",
        "Ukhia",
        "Pakua",
    ],
    "Dhaka": [
        "Jatrabari",
        "Asulia",
        "Khilgaon",
        "Savar",
        "Turag",
        "Mohammadpur (Dhaka)",
        "Kafrul",
        "Chak Bazar",
        "Dakhkhin Khan",
        "Keranigonj",
        "Badda",
        "Mirpur",
        "Kotwali ( Dhaka)",
        "New Market",
        "Shampur",
        "Shah Ali",
        "Dhamrai",
        "Rampura",
        "Nababgonj (Dhaka)",
        "Sobujbagh",
        "South Keranigonj",
        "Lalbagh",
        "Sher-E-Bangla Nagar",
        "Banani",
        "Dohar",
        "Motijheel",
        "Tejgaon",
        "Kadamtoli",
        "Uttara",
        "Mugda",
        "Shahjahanpur",
        "Ramna",
        "Rupnager",
        "Vatara",
        "Bongsal",
        "Gendaria",
        "Sutrapur",
        "Wari",
        "Kamrangirchar",
        "Shahabagh",
        "Paltan",
        "Demra",
        "Gulsan",
        "Tejgaon IND",
        "Khilkhet",
        "Biman Bondor(Dhaka)",
        "Uttara West",
        "Uttar Khan",
        "Dhanmondi",
        "Hazaribagh",
        "Kalabagan",
        "Adabor",
        "Gabtoli(Dhaka)",
        "Pallabi",
        "Vasantek",
        "Cantonment",
    ],
    "Dinajpur": [
        "Dinajpur Sadar",
        "Birgonj",
        "Parbotipur",
        "Birampur",
        "Hakimpur",
        "Fulbari",
        "Chirirbondor",
        "Nababgonj (Dinajpur)",
        "Birol",
        "Bochagonj(Setabgonj)",
        "Kaharol",
        "Khansama",
        "Ghoraghat",
    ],
    "Faridpur": [
        "Faridpur Sadar",
        "Modhukhali",
        "Alfadanga",
        "Nagarkanda",
        "Vanga",
        "Boalmari",
        "Sadarpur",
        "Charbhadrasan",
        "Saltha",
    ],
    "Feni": [
        "Feni Sadar",
        "Chagolnaia",
        "Porsuram",
        "Dagonbhuiya",
        "Fulgazi",
        "Sonagazi",
    ],
    "Gaibandha": [
        "Fulchori",
        "Gobindagonj",
        "Sundargonj",
        "Gaibandha Sadar",
        "Sadullapur",
        "Shaghata",
        "Palasbari",
    ],
    "Gazipur": [
        "Tongi",
        "Joydevpur (Gazipur)",
        "Sreepur",
        "Kaliakor",
        "Kapasia",
        "Kaligonj (Gazipur)",
    ],
    "Gopalgonj": ["Kotalipara", "Gopalgonj Sadar", "Tungipara", "Muksudpur", "Kasiani"],
    "Hobigonj": [
        "Hobigong Sadar",
        "Madhabpur",
        "Sayestagonj",
        "Nobigonj",
        "Chunarughat",
        "Bahubol",
        "Lakhai",
        "Azmirigonj",
        "Baniachang",
    ],
    "Jamalpur": [
        "Sarisabari",
        "Islampur",
        "Jamalpur Sadar",
        "Boksigonj",
        "Dewangonj",
        "Melandah",
        "Madargonj",
    ],
    "Jessore": [
        "Jessore Sadar",
        "Sarsa(Benapol)",
        "Chowgacha",
        "Avoynagor",
        "Zikoregacha",
        "Kesobpur",
        "Bagherpara",
        "Monirampur",
    ],
    "Jhalakathi": ["Jhalakathi Sadar", "Rajapur", "kathalia", "Nolchiti"],
    "Jhenaidah": [
        "Coatchandpur",
        "Jhenaidah Sadar",
        "Horinakundu",
        "Kaligonj (Jhenaidah)",
        "Mohespur",
        "Shoilkupa",
    ],
    "Joypurhat": ["Joypurhat Sadar", "Akkelpur", "Panchbibi", "Kalai", "Khetlal"],
    "Khagracahri": [
        "Khagrachari Sadar",
        "Ramgor",
        "Matiranga",
        "Mohalchori",
        "Dighinala",
        "Panchori",
        "Manikchori",
        "Luxmichori",
    ],
    "Khulna": [
        "Khulna Sadar",
        "Khalishpur",
        "Fultola",
        "Paikgacha",
        "Dumuria",
        "Khan Jhahan Ali",
        "Daulatpur (Khulna)",
        "Sonadanga",
        "Tarokhada",
        "Rupsa",
        "Dakop",
        "Batiaghata",
        "Dighalia",
        "Koyra",
    ],
    "Kishoregonj": [
        "Kishoregonj Sadar",
        "Bhairab",
        "Bajitpur",
        "Pakundia",
        "Karimgonj",
        "Kotiadi",
        "Tarail",
        "Hosenpur",
        "Kuliarchar",
        "Nikli",
        "Itna",
        "Mitamoin",
        "Astragram",
    ],
    "Kurigram": [
        "Kurigram Sadar",
        "Ulipur",
        "Fulbari(Kurigram)",
        "Rowmari",
        "Nagessori",
        "Bhurungamari",
        "Rajibpur",
        "Kochakata",
        "Rajarhat",
        "Chilmari",
    ],
    "Kushtia": [
        "Kushtia Sadar",
        "Mirpur (Kushtia)",
        "Bheramara",
        "Daulatpur (Kushtia)",
        "Khoksha",
        "E.B. (Horinarayanpur)",
        "Kumarkhali",
    ],
    "Lalmonirhat": [
        "Lalmonirhat Sadar",
        "Patgram",
        "Aditmari",
        "Hatibandha",
        "Kaligonj(Lalmonirhat)",
    ],
    "Laxmipur": [
        "Laxmipur Sadar",
        "Raipur",
        "Ramgonj",
        "Chandragonj",
        "Komolnager",
        "Ramgoti",
    ],
    "M.Bazar": [
        "M.Bazar Sadar",
        "Kulaura",
        "Sreemongol",
        "Borolekha",
        "Juri",
        "Komolgonj",
        "Raznager",
    ],
    "Madaripur": ["Sibchar", "Madaripur Sadar", "Rajor", "Kalkini"],
    "Magura": ["Magura Sadar", "Shreepur ( Magura)", "Mohammadpur (Magura)", "Salikha"],
    "Manikgonj": [
        "Manikgonj Sadar",
        "Saturia",
        "Singair",
        "Ghior",
        "Daulatpur (Manikgonj)",
        "Horirampur (Zitka)",
        "Sibaloy",
    ],
    "Meherpur": ["Meherpur Sadar", "Gangni", "Mozibnager"],
    "Munshigonj": [
        "Sirajdikhan",
        "Tongibari",
        "Sree Nagar",
        "Gojaria",
        "Munshigonj Sadar",
        "Lawhojong",
    ],
    "Mymensingh": [
        "Mymensingh Sadar",
        "Muktagacha",
        "Valuka",
        "Haluaghat",
        "Gowripur",
        "Trisal",
        "Goforgaon",
        "Nandail",
        "Fulpur",
        "Dhobaura",
        "Tarakanda",
        "Fulbaria (M.Sing)",
        "Ishwargonj",
    ],
    "Naogaon": [
        "Naogaon Sadar",
        "Mohadebpur",
        "Sapahar",
        "Niamatpur",
        "Patnitala (Nozipur)",
        "Manda",
        "Atrai",
        "Raninager",
        "Bodolgachi",
        "Porsha",
        "Dhamurhat",
    ],
    "Narail": ["Lohagora (Narail)", "Narail Sadar", "Kalia", "Noragati"],
    "Narayangonj": [
        "Narayangonj Sadar",
        "Rupgonj",
        "Sonargaon",
        "Siddirgonj",
        "Fatulla",
        "Araihazar",
        "Bondor (N Gonj)",
    ],
    "Narsingdi": [
        "Narsingdi Sadar",
        "Raipura",
        "Monohordi",
        "Polas",
        "Belabo",
        "Sibpur",
    ],
    "Natore": [
        "Natore Sadar",
        "Lalpur",
        "Boraigram",
        "Bagatipara",
        "Naldanga",
        "Singra",
        "Gurudaspur",
    ],
    "Netrokona": [
        "Netrokona Sadar",
        "Kolmakanda",
        "Mohongonj",
        "Purabadhala",
        "Durgapur (Netrakona)",
        "Modon",
        "Barhatta",
        "Atpara",
        "Kendua",
        "khaliajuri",
    ],
    "Nilphamari": [
        "Syedpur",
        "Domar",
        "Nilphamari Sadar",
        "Kishoregonj",
        "Dimla",
        "Jaldhaka",
    ],
    "Noakhali": [
        "Begumgonj",
        "Chatkhil",
        "Companigonj (Noakhali)",
        "Hatia",
        "Sonaimuri",
        "Senbagh",
        "Sudharam",
        "Subarnachar",
        "Kabirhat",
    ],
    "Pabna": [
        "Pabna Sadar",
        "Ishwardi",
        "Sathia",
        "Chatmohor",
        "Sujanagar",
        "Bera",
        "Atghoria",
        "Vangura",
        "Ataikula",
        "Faridpur(Pabna)",
    ],
    "Panchagar": ["Panchagar Sadar", "Debigonj", "Boda", "Tetulia", "Atwari"],
    "Patuakhali": [
        "Baofal",
        "Patuakhali Sadar",
        "Kolapara",
        "Mirzagonj",
        "Dumki",
        "Galachipa",
        "Dosmina",
        "Rangaboli",
    ],
    "Pirojpur": [
        "Nesarabad ( Sarupkati)",
        "Pirojpur Sadar",
        "Kaokhali",
        "Vandaria",
        "Mothbaria",
        "Nazirpur",
        "Zianagar",
    ],
    "Rajbari": ["Rajbari Sadar", "Pangsa", "Baliakandi", "Goalando", "Kalukhali"],
    "Rajshahi": [
        "Boalia ( Sadar)",
        "Puthia",
        "Bagha",
        "Mohonpur",
        "Rajpara",
        "Poba",
        "Bagmara",
        "Tanor",
        "Shah Mukhdum",
        "Motihar",
        "Katakhali",
        "Godagari",
        "Charghat",
        "Durgapur (Rajshahi)",
    ],
    "Rangamati": [
        "Rangamati Sadar",
        "Kaptai",
        "Langadu",
        "Baghaichari",
        "Kawkhali (Rangamati)",
        "Nanner Char",
        "Borokol",
        "Juraichori",
        "Razostoli",
        "Bilaichori",
    ],
    "Rangpur": [
        "Rangpur Sadar",
        "Bodorgonj",
        "Pirgonj (Rangpur)",
        "Mithapukur",
        "Pirgacha",
        "Gangachara",
        "Taragonj",
        "Kawnia",
    ],
    "Satkhira": [
        "Satkhira Sadar",
        "Samnagar",
        "Kolaroa",
        "Ashasuni",
        "Debhata",
        "Kaligonj (Satkhira)",
        "Patkelghata",
        "Tala",
    ],
    "Shariatpur": [
        "Palong (Sariatpur)",
        "Naria",
        "Janzira",
        "Vedorgonj",
        "Damudda",
        "Gosairhat",
        "Shokipur",
    ],
    "Sherpur": ["Sherpur Sadar", "Nokhla", "Nolitabari", "Sreebordi", "Jhenaigati"],
    "Sirajgonj": [
        "Sirajgonj Sadar",
        "Ullapara",
        "Belkuchi",
        "Raigonj",
        "Shahjadpur",
        "Kazipur",
        "Tarash",
        "Solonga",
        "Kamarkhond",
        "Enayetpur",
        "Chawhali",
    ],
    "Sunamgonj": [
        "Duarabazar",
        "Sunamgonj Sadar",
        "Derai",
        "Chatak",
        "Dharmapasa",
        "Taherpur (Sunamgonj)",
        "Jagannathpur",
        "Dakhkhin Sunamgonj",
        "Salla",
        "Bishombharpur",
        "Jamalgonj",
        "Moddhonager",
    ],
    "Sylhet": [
        "Sylhet Sader",
        "Golapgonj",
        "Jokigonj",
        "Osmaninagar",
        "Bianibazar",
        "Shah Poran",
        "Fenchugonj",
        "Jalalabad",
        "South Surma",
        "Goainghat",
        "Jaintapur",
        "Companigonj (Sylhet)",
        "Bishwanath",
        "Kanaighat",
        "Balagonj",
    ],
    "Tangail": [
        "Tangail Sadar",
        "Mirzapur",
        "Basail",
        "Sokhipur",
        "Vhuapur",
        "Ghatail",
        "Nagorpur",
        "Modhupur",
        "Dhonobari",
        "Kalihati",
        "Deldoar",
        "Gopalpur",
    ],
    "Thakurgaon": [
        "Thakurgaon Sadar",
        "Ranisankail",
        "Pirgonj(Thakurgoan)",
        "Baliadangi",
        "Horipur",
    ],
}
